# Generated by Django 5.2.10 on 2026-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('posts', 'posts'), ('users', 'users'), ('bitcoin', 'bitcoin'), ('quotes', 'quotes'), ('books', 'books')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('api', 'API'), ('endpoint', 'endpoint'), ('html', 'HTML')], max_length=16)),
                ('base_url', models.URLField(max_length=300)),
                ('path', models.CharField(default='/', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
